# Generated by Django 2.1.7 on 2021-02-10 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210209_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 9, 22, 34, 1, 869024)),
        ),
    ]
